### ISSUE TITLE
Is there a requirements.txt file for this project? How do I set the project up and install the relevant libraries?

### ISSUE THREAD

**Issue by charlbury** [Azure-Samples/azure-monitor-opencensus-python#3]
Is there a requirements.txt file for this project? How do I set the project up and install the relevant libraries?

**Comment by lzchen** [comment]
You cannot install the sample app as it is not a hosted Python package. Simply git clone the repository and follow the [usage](https://github.com/Azure-Samples/azure-monitor-opencensus-python#usage) guidelines.
